version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: optifit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: optifit
    volumes:
      - user_service_source:/usr/src/app
      - user_service_node_modules:/usr/src/app/node_modules
    command: npm run start:dev

# Uncomment and configure these services as needed:
#  logging-service:
#    build:
#      context: ./services/logging-service
#      dockerfile: Dockerfile
#    ports:
#      - "3001:3000"
#    depends_on:
#      - db
#
#  ai-service:
#    build:
#      context: ./services/ai-service
#      dockerfile: Dockerfile
#    ports:
#      - "3002:3000"
#    depends_on:
#      - db

volumes:
  pgdata:
  user_service_source:
  user_service_node_modules:
